# Generated by Django 5.2 on 2025-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCliente', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('especiePet', models.CharField(max_length=100)),
                ('nomePet', models.CharField(max_length=100)),
                ('portePet', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(choices=[('Pendente ', 'Pendente '), ('Confirmado ', 'Confirmado '), ('Concluído ', 'Concluído '), ('Cancelado ', 'Cancelado ')], default='Pendente ', max_length=100)),
            ],
        ),
    ]
