# Generated by Django 4.2.20 on 2025-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='servico',
            field=models.CharField(choices=[('Veterinario', 'Atendimento Veterinário'), ('BanhoTosa', 'Banho & Tosa'), ('Adestramento', 'Adestramento'), ('Adocao', 'Adoção')], default='teste', max_length=20),
            preserve_default=False,
        ),
    ]
